name: Run Gradle on push

on: [push]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
      # run only if 'workflows' files were changed
      - name: workflow tests
        if: steps.filter.outputs.workflows == 'true'
        run: echo "Workflow file"
      
      # run only if not 'workflows' files were changed
      - name: not workflow tests
        if: steps.filter.outputs.workflows != 'true'
        run: echo "NOT workflow file"
        
  appointment-microservice-build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.appointment-service }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            appointment-service:
              - 'appointment-service/**'
        if: steps.filter.outputs.appointment-service == 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle Build
        working-directory: appointment-service
        run: ./gradlew build

  chat-microservice-build:
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        working-directory: chat-service
        run: ./gradlew build

  user-auth-microservice-build:
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        working-directory: user-auth-service
        run: ./gradlew build