name: Run Gradle on push

on: [push]

jobs:
  appointment-service-check:
    runs-on: ubuntu-latest
    outputs:
      diff-true: ${{ steps.filter.outputs.appointment-service }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            appointment-service:
              - 'appointment-service/**'
      - name: changed
        if: steps.filter.outputs.appointment-service == 'true'
        run: echo "File changed"

      - name: not changed
        if: steps.filter.outputs.appointment-service == 'true'
        run: echo "File not changed"

  appointment-microservice-build:
    needs: appointment-service-check
    runs-on: ubuntu-latest
    if: needs.appointment-service-check.outputs.diff-true == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle Build
        working-directory: appointment-service
        run: ./gradlew build

  chat-microservice-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        working-directory: chat-service
        run: ./gradlew build

  user-auth-microservice-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        working-directory: user-auth-service
        run: ./gradlew build